### ISSUE TITLE
Crash on server.

### ISSUE THREAD

**Issue by Sunekaer** [zuve/SearchableChest#1]
forge-1.14.4-28.1.70
searchablechests-1.14-1.5.2

https://paste.dimdev.org/jesuxuqaso.rb

**Comment by zuve** [comment]
Appears to be an issue loading the IToolTipFlag interface, but I suspect its forge related as another mod had the exact same issue based on that log.

**Comment by trevorjd** [comment]
Still happening with Forge 28.1.104 and SearchChest 1.5.3.

EnchDesc 1.14.4-1.3.8 (latest at time of writing) seems to have resolved the issue for them. Perhaps you could contact the author there and see how they got around it.

**Comment by ZadenRB** [comment]
Sorry for the late response. Should be fixed in 1.5.4. Regardless, is a client-side mod, i've updated the description to specify.

**Comment by zuve** [comment]
Should be fixed in latest versions
